[WIP] Czech language
Froxlor/Froxlor pull request #870
Opened 2020-07-15 20:51 UTC by rex2630

# Description

Just language addition

# How Has This Been Tested?

Not yet

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-11-12 08:02 UTC, d00p requested changes
Filename is not correct, it should be `.lng.php` not `.Ing.php` (lower L, you got an upper I)

2021-07-21 17:57 UTC, d00p reviewed
Still WIP or ready to merge?

2021-07-21 17:58 UTC, d00p approved these changes

2021-07-21 18:31 UTC, rex2630 commented
There are lot of strings to do and i dont know if i can do all of them soon, so if u want u can merge it like that and i will improve it in future pull requests or anyone can do. I dont have so much time to update is so frequently, sorry.

2021-07-21 18:41 UTC, merged